name = "default"
success_text = "#00FF00"
error_text = "#CC0000"
highlight_text = "#00FFFF"
spinner = "5"
prompt_title = "5"
prompt_default = "1"
key_text = "#FF79C6"
value_text = "#8BE9FD"
table_header = "5"
table_id = "6"
table_format = "2"
table_metric = "3"
table_repeating = "4"
message_error = "#FF0000"
message_success = "#00FF00"
message_other = "#00FFFF"
