name = "graphite"
success_text = "#B0BEC5"
error_text = "#EF5350"
highlight_text = "#90CAF9"
spinner = "#78909C"
prompt_title = "#78909C"
prompt_default = "#FFB74D"
key_text = "#CE93D8"
value_text = "#80DEEA"
table_header = "#78909C"
table_id = "#90A4AE"
table_format = "#AED581"
table_metric = "#FFE082"
table_repeating = "#9FA8DA"
message_error = "#EF5350"
message_success = "#B0BEC5"
message_other = "#90CAF9"
