name = "nord"
success_text = "#A3BE8C"
error_text = "#BF616A"
highlight_text = "#88C0D0"
spinner = "#81A1C1"
prompt_title = "#81A1C1"
prompt_default = "#D08770"
key_text = "#B48EAD"
value_text = "#8FBCBB"
table_header = "#81A1C1"
table_id = "#88C0D0"
table_format = "#A3BE8C"
table_metric = "#EBCB8B"
table_repeating = "#5E81AC"
message_error = "#BF616A"
message_success = "#A3BE8C"
message_other = "#88C0D0"
