name = "sunset"
success_text = "#43A047"
error_text = "#E53935"
highlight_text = "#00ACC1"
spinner = "#FB8C00"
prompt_title = "#FB8C00"
prompt_default = "#F4511E"
key_text = "#8E24AA"
value_text = "#039BE5"
table_header = "#FB8C00"
table_id = "#1E88E5"
table_format = "#43A047"
table_metric = "#FDD835"
table_repeating = "#3949AB"
message_error = "#E53935"
message_success = "#43A047"
message_other = "#00ACC1"
